### ISSUE TITLE
Intigrate with coreos prometheus-operator

### ISSUE THREAD

**Issue by madushan1000** [dbsystel/alertmanager-config-controller#3]
Hi, 
Do you have any intentions to integrate this with prometheus-operator? Maybe using a couple of new crd types? I'm looking into this right now, my knowledge of prometheus-operator design is limited :/

Related prometheus-operator issue(https://github.com/coreos/prometheus-operator/issues/2258)

**Comment by Kirchen99** [comment]
Let us discuss this in https://github.com/coreos/prometheus-operator/issues/2258
